config/routes.rb
Rails.application.routes.draw do
   root "posts#home"

  resources :posts do
    resources :comments
  end
  
  resources :comments do
    resources :comments
  end

  get 'auth/:provider/callback', to: "sessions#create"

  delete 'sign_out', to: "sessions#destroy", as: 'sign_out'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, as: :commentable, dependent: :destroy
	belongs_to :user, :foreign_key => 'user_id'
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :post, :foreign_key => "user_id", dependent: :destroy

	def self.sign_in_from_omniauth(auth)
		find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
	end

	def self.create_user_from_omniauth(auth)
		create(
			provider: auth['provider'],
			uid: auth['uid'],
			name: auth['info']['name']
			)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    if current_user.nil?
      flash[:error] = 'You must be signed in to view that page.'
      redirect_to root_path

    end
  end

  helper_method :current_user, :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   
   before_action :find_commentable, :authenticate_user!

	def create
		    
    @comment = @commentable.comments.new comment_params
   
    
     if @comment.save
       respond_to do |format|
       
       format.js {redirect_to :back}
       end
     end 
    end

    private

    def comment_params
      params.require(:comment).permit(:body)
    end

    def find_commentable
      @commentable = Comment.find(params[:comment_id]) if params[:comment_id]
      @commentable = Post.find(params[:post_id]) if params[:post_id]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	respond_to :html
    respond_to :js
    before_action :set_auth
    before_filter :authenticate_user!, except: [:home, :index]
   

    def home
    	if current_user
    		redirect_to posts_path
        end
    end

	def index
	    @post = Post.new
		@posts = Post.all.includes(:comments).order('created_at DESC')
	end

	def show
	end
    
 	def create
		@post = Post.new(post_params)
		@post.user = current_user

		if @post.save
		   redirect_to :back
		end   
	end
    
	def edit
		@post = current_user.post.find(params[:id])
	end

	def update
	    @post = current_user.post.find(params[:id])
        
	    if @post.update(params[:post].permit(:body))
	     	redirect_to :back
	    else
	     	render 'edit'
	    end
	end

	def destroy
		@post = current_user.post.find(params[:id])
		@post.destroy 

		redirect_to :back
	end



	private
	    def post_params
	    	params.require(:post).permit(:body, :user_id)
	    end

	    def set_auth
	    	@auth = session[:omniauth] if session[:omniauth]
	    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		auth = request.env["omniauth.auth"]
		session[:omniauth] = auth.except('extra')
		user = User.sign_in_from_omniauth(auth)
		session[:user_id] = user.id
		redirect_to root_url, notice: "SIGNED IN"
	end

	def destroy
		session[:user_id] = nil
		session[:omniauth] = nil
		redirect_to root_url, notice: "SIGNED OUT"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_comment.html.erb
  
<li>
     <div class="comment-meta"> 
				<span class="entry-meta">&nbsp;&nbsp;<%= time_ago_in_words(comment.created_at) %> ago</span>
		 </div><!--comment-meta-->
			 <p>
          <%= comment.body %>
       </p>
           
    <% if current_user %>
 
    <div class="respond">
       <%= form_for [comment, Comment.new], remote: true do |f| %>
         <%= f.text_field :body, placeholder: "Add a Reply" %>
         <%= f.submit "Reply", class: "submit-comment", data: { no_turbolink: true } %>
         <% end %>
    </div>

    <% end %>



  <ul>
      <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
 <%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div id="main-content" class="wrapper clearfix">
	<div class="container clearfix">
		<div  class="inner-box">
			<%= form_for @post, :html => {:class => 'submit_form', :id => 'comments-form'}, remote: true do |f| %>
   	            <p class="textarea-block">
	                <%= f.text_area :body, placeholder: "Put your text here", cols: 120, rows: 10, :required => true %>
	                <%= f.submit "Create", id: 'submit-comment' %>
	            </p>
            <% end %>
            <div class="clear"></div> 
		</div>
	</div>
</div>

app/views/posts/_main.html.erb
<header id="header">
  <div class="wrapper">
    <h1 id="logo-image">
      <p>Для добавления и комментирования сообщений выполните вход</p>
      <ul>
        <li><%= link_to "auth/facebook" do %><%= image_tag('facebook.ico', width: '50', height: '50')%></li>
        <% end %>
      </ul>
    </h1>
  </div><!--end:wrapper-->
</header>

<% if @posts.any? %>

  <% @posts.each do |post| %>
    
    <%= render post %>

    <div class="wrapper">
   
      <% if post.comments.any? %>

        <div class="entry-box-header clearfix">
           
          <span>All comments</span>

          <ul class="respond">
            <%= render :partial => post.comments %>
          </ul>

        </div>
          
      <% end %>

    </div>

  <% end %>

<% else %>

  <h1 id="logo-image">No Posts found</h1>

<% end %>

app/views/posts/_post.html.erb
<div class="wrapper clearfix">
	<div class="container clearfix">
		<section class="inner-box clearfix">
            <%= div_for post do %>
                <article class="entry-item">
				    <header>
					    <span class="entry-meta"><%= post.created_at.strftime("%B, %d, %Y")%></span>          
				    </header>	
				    <hr>
    	            <p><%= post.body %></p>
    	        </article>
            <% end %>
        </section>
    </div>
</div>

app/views/posts/_user_main.html.erb
<header id="header">
  <div class="wrapper">
    <h1 id="logo-image">
      <ul>
        <li><%= current_user.name %> - <%= image_tag(@auth['info']['image'], width: '50', height: '50')%></li>
        <li><%= link_to "Sign Out", 'sign_out', method: :delete %></li>
      </ul>
    </h1>
  </div><!--end:wrapper-->
</header>

<%= render 'form' %>

<% if @posts.any? %>
  <% @posts.each do |post| %>

        <%= render 'user_post', post: post %>

    <div class="wrapper">
       
          <div class="respond">
            <h3 id="reply-title">Leave your comment</h3>

            <%= form_for [post, Comment.new], :html => {:class => 'form_content comments-form'}, remote: true do |f| %>
              <p class="textarea-block">
                <%= f.text_field :body, placeholder: "Add a Comment", :required => true %>
              </p>
              <p class="form-submit">
                <%= f.submit "Comment", class: "submit-comment", data: { no_turbolink: true } %>
              </p>
            <% end %>

          </div>

      
      <% if post.comments.any? %>
      <div class="entry-box-header clearfix">
        <span>All comments</span>
         
       
        <ul id="<%= post.id %>" class="respond">
          <%= render :partial => post.comments %>
        </ul>
       
      </div>
      <% end %>
    </div>
  <% end %> 

<% else %>

  <h1 id="logo-image">No Posts found</h1>

<% end %>

app/views/posts/_user_post.html.erb
<div class="wrapper clearfix">
	<div class="container clearfix">
		<section class="inner-box clearfix">
		  <%= div_for post do %>
			  <article class="entry-item">
				  <header>
					  <span class="entry-meta"><%= post.created_at.strftime("%B, %d, %Y")%></span>          
				  </header>	
				  <hr>
    	    <p><%= post.body %></p>
    	  </article>

        <% if post.user_id == current_user.id %>
          <div class="social-share clearfix">
                                  	    
   	        <%= link_to 'Edit', edit_post_path(post), class: "submit-comment", remote: true %>
   	                        
   	        <%= link_to 'Delete', post, remote: true, class: "submit-comment", method: :delete, data: {confirm: 'Are you sure about that?'} %>
 	                   
   	      </div>
        <% end %>
      <% end %>
    </section>
  </div>
</div>

app/views/posts/edit.js.erb
$('form').hide();
$('div#<%= dom_id(@post) %>').replaceWith('<%= j render("form") %>');

app/views/posts/home.html.erb
<header id="header">
	
	<div class="wrapper">
			<h1 id="logo-image">
				<%= link_to "auth/facebook" do %><%= image_tag('facebook.ico', width: '80', height: '80')%>
                <% end %>
                <p>
                	or<br>
                <%= link_to "Guest access", posts_path %>
                </p>
			</h1>
		
	</div><!--end:wrapper-->
</header>

app/views/posts/index.html.erb
  <%if current_user %>
      <%= render 'user_main'%>
  <% else %>
      <%= render 'main' %>
  <% end %>

app/views/posts/update.js.erb
$('form').hide();
$('div#<%= dom_id(@post) %>').replaceWith('<%= j render partial: "post", locals: {post: @post} %>');